datadog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("transportation_management.urls", namespace="transportation-management")),
]

transportation_management/urls.py
from django.conf.urls import url
from .views import index, login, authenticate, create, list, read
from django.contrib.auth.views import logout

app_name = 'transportation_management'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^create/', create, name='create'),
    url(r'^read/(?P<id>\d+)/$', read, name='read'),
    url(r'^list/', list, name='list'),
    url(r'^authenticate/', authenticate, name='authenticate'),
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, kwargs={"next_page": "/login"}, name="logout"),
]

transportation_management/models.py
from datetime import timedelta
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Vehicle(models.Model):
    class Meta:
        verbose_name = _('Vehicle')
        verbose_name_plural = _('Vehicle')

    vehicle_name = models.CharField(max_length=254)
    takes_fuel_while_standing = models.PositiveIntegerField()  # liter/hour
    takes_fuel_while_moving = models.PositiveIntegerField()  # liter/hour
    takes_fuel_while_unloading = models.PositiveIntegerField()  # liter/hour

    def __str__(self):
        return 'Vehicle: {}'.format(self.vehicle_name)


class TravelReport(models.Model):
    class Meta:
        verbose_name = _('Travel Report')
        verbose_name_plural = _('Travel Report')

    vehicle = models.ForeignKey(Vehicle)
    route = models.CharField(max_length=254)
    date = models.DateField()
    time_left_terminal = models.TimeField()
    time_arrived_to_client = models.TimeField()
    time_left_client = models.TimeField()
    time_back_to_terminal = models.TimeField()
    time_unloading = models.PositiveIntegerField()  # in minutes
    speedometer_at_leaving = models.PositiveIntegerField()
    speedometer_at_arrival = models.PositiveIntegerField()

    @property
    def distance(self):
        return self.speedometer_at_arrival - self.speedometer_at_leaving

    @property
    def fuel_consumed(self):
        t1 = timedelta(hours=self.time_left_terminal.hour, minutes=self.time_left_terminal.minute)
        t2 = timedelta(hours=self.time_arrived_to_client.hour, minutes=self.time_arrived_to_client.minute)
        t3 = timedelta(hours=self.time_left_client.hour, minutes=self.time_left_client.minute)
        t4 = timedelta(hours=self.time_back_to_terminal.hour, minutes=self.time_back_to_terminal.minute)
        timedelta_standing = (t3 - t2 - timedelta(minutes=self.time_unloading))
        timedelta_moving = (t2 - t1) + (t4 - t3)
        time_standing_sec = self._timedelta_to_sec(timedelta_standing)
        time_moving_sec = self._timedelta_to_sec(timedelta_moving)
        time_unloading_sec = self.time_unloading * 60
        fuel_consumed_standing = self._fual_consumption(self.vehicle.takes_fuel_while_standing, time_standing_sec)
        fuel_consumed_moving = self._fual_consumption(self.vehicle.takes_fuel_while_moving, time_moving_sec)
        fuel_consumed_unloading = self._fual_consumption(self.vehicle.takes_fuel_while_unloading, time_unloading_sec)
        return round(fuel_consumed_standing + fuel_consumed_moving + fuel_consumed_unloading, 2)

    def _timedelta_to_sec(self, time_delta):
        """
        :param time_delta: 
        :return: int seconds:
        """
        t = str(time_delta)
        h, m, s = t.split(':')
        time_in_sec = int(h) * 3600 + int(m) * 60 + int(s)
        return time_in_sec

    def _fual_consumption(self, consumes_per_hour, time_consuming_in_seconds):
        return round(float(consumes_per_hour) / float(60 * 60) * time_consuming_in_seconds, 2)

    def __str__(self):
        return '<TravelReport: {}>'.format(self.id)

transportation_management/forms.py
import datetime
from django import forms
from django.contrib.auth import authenticate
from django.utils.translation import ugettext as _

from transportation_management.models import TravelReport


class AuthenticationForm(forms.Form):
    default_error_messages = {
        'invalid_username': _('Username is invalid.'),
        "required_username": _("Username is required."),
        "required_password": _("Password is required."),
    }

    error_messages = {
        'invalid_login': _("Username and/or password is invalid."),
        'inactive': _("This account is inactive."),
    }

    username = forms.CharField(max_length=254, error_messages={"required": default_error_messages["required_username"],
                                                               "invalid": default_error_messages["invalid_username"]})
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput(),
                               error_messages={"required": default_error_messages["required_password"]})

    def __init__(self, *args, **kwargs):
        self.user_cache = None
        super(AuthenticationForm, self).__init__(*args, **kwargs)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            self.user_cache = authenticate(username=username, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(self.error_messages['invalid_login'])
            elif not self.user_cache.is_active:
                raise forms.ValidationError(self.error_messages['inactive'])
        return self.cleaned_data

    def get_user(self):
        return self.user_cache


class TravelReportForm(forms.ModelForm):
    class Meta:
        model = TravelReport
        fields = ['vehicle', 'route', 'date', 'time_left_terminal', 'time_arrived_to_client',
                  'time_left_client', 'time_back_to_terminal', 'time_unloading',
                  'speedometer_at_leaving', 'speedometer_at_arrival']

        error_messages = {
            'vehicle': {
                "required": _('Vehicle is required.'),
                "invalid": _('Vehicle is invalid.'),
            },
            'route': {
                "required": _('Route is required.'),
                "invalid": _('Route is invalid.')
            },
            'date': {
                "required": _('Date is required.'),
                "invalid": _('Date is invalid.')
            },
            'time_left_terminal': {
                "required": _('Time left terminal is required.'),
                "invalid": _('Time left terminal is invalid.')
            },
            'time_arrived_to_client': {
                "required": _('Time arrived to client is required.'),
                "invalid": _('Time arrived to client is invalid.')
            },
            'time_left_client': {
                "required": _('Time left the client is required.'),
                "invalid": _('Time left the client is invalid.')
            },
            'time_back_to_terminal': {
                "required": _('Time back to the terminal is required.'),
                "invalid": _('Time back to the terminal is invalid.')
            },
            'time_unloading': {
                "required": _('Unloading time is required.'),
                "invalid": _('Unloading time is invalid.')
            },
            'speedometer_at_leaving': {
                "required": _('Speedometer at leaving is required.'),
                "invalid": _('Speedometer at leaving is invalid.')
            },
            'speedometer_at_arrival': {
                "required": _('Speedometer at arrival is required.'),
                "invalid": _('Speedometer at arrival is invalid.')
            },
        }

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.pop('instance', None)
        self.initial = self.get_initial()
        super(TravelReportForm, self).__init__(initial=self.initial, instance=self.instance, *args, **kwargs)

    def get_initial(self):
        initial = {'vehicle': '',
                   'route': '',
                   'date': datetime.datetime.now().date().strftime("%m/%d/%Y"),
                   'time_left_terminal': '',
                   'time_arrived_to_client': '',
                   'time_left_client': '',
                   'time_back_to_terminal': '',
                   'time_unloading': '',
                   'speedometer_at_leaving': '',
                   'speedometer_at_arrival': ''}
        return initial

transportation_management/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import login as user_login
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required

from transportation_management.models import Vehicle, TravelReport
from .forms import AuthenticationForm, TravelReportForm


@never_cache
@require_http_methods(["GET", "POST"])
def authenticate(request):
    vars = {}
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
    else:
        form = AuthenticationForm(request.POST or None)
        vars['form'] = form
        if form.is_valid():
            user = form.get_user()
            user_login(request, user)
            if user.is_staff:
                return HttpResponseRedirect('/list/')
            else:
                return HttpResponseRedirect('/create/')

    return render(request, 'transportation_management/login.html', vars)


@require_http_methods(['GET'])
def login(request):
    vars = {}

    return render(request, 'transportation_management/login.html', vars)


@login_required
@require_http_methods(['GET'])
def index(request):
    vars = {}

    return render(request, 'transportation_management/index.html', vars)


@login_required
@require_http_methods(['POST', 'GET'])
def create(request):
    vars = {}
    vars['vehicles'] = Vehicle.objects.all()
    form = TravelReportForm(request.POST or None)
    vars['form'] = form
    if form.is_valid():
        travel_report = form.save()
        print(travel_report)
        return HttpResponseRedirect(reverse('transportation_management:read', kwargs={'id': travel_report.id}))

    return render(request, 'transportation_management/create.html', vars)


@login_required
@require_http_methods(['GET'])
def read(request, id):
    vars = {}
    travel_report = get_object_or_404(TravelReport, pk=id)
    vars['travel_report'] = travel_report

    return render(request, 'transportation_management/read.html', vars)


@login_required
@require_http_methods(['GET'])
def list(request):
    vars = {}
    vars['travel_reports'] = TravelReport.objects.all()

    return render(request, 'transportation_management/list.html', vars)

templates/transportation_management/create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/data_common.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/create.css' %}"/>
{% endblock extra_css %}

{% block content %}
    <div class="submit-transport-report">
        <h1>Create travel record</h1>

        {% if form or error %}
            {% if form.errors or error %}
                <div class="alert alert-danger no-margin fade in">
                    <button class="close" data-dismiss="alert">
                        x
                    </button>
                    <ul>
                        {% for error,msg in form.errors.items %}
                            <li>{{ msg.as_text|escape|slice:"2:" }}</li>
                        {% endfor %}
                        {% if error %}
                            <li>{{ error }}</li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        {% endif %}
        <form class="form-horizontal" action="{% url 'transportation-management:create' %}" method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="vehicle" class="col-sm-2 control-label">Vehicle</label>
                <div class="col-sm-6">
                    <select class="form-control" name="vehicle">
                        <option value="">Select vehicle</option>
                        {% for vehicle in vehicles %}
                            <option value="{{ vehicle.id }}">{{ vehicle.vehicle_name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="route" class="col-sm-2 control-label">Route</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" name="route" value="{{ form.route.value }}"
                           placeholder="Route">
                </div>
            </div>

            <div class="form-group">
                <label for="time_unloading" class="col-sm-2 control-label">Date</label>
                <div class="col-sm-6 input-group date" data-provide="datepicker">
                    <input type="text" class="form-control" name="date" value="{{ form.date.value }}">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-th"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="time_left_terminal" class="col-sm-2 control-label">Time left terminal</label>
                <div class="col-sm-6 input-group bootstrap-timepicker timepicker">
                    <input id="timepicker1" type="text" name="time_left_terminal"
                           value="{{ form.time_left_terminal.value }}"
                           class="form-control input-small">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                </div>
            </div>
            <div class="form-group">
                <label for="time_arrived_to_client" class="col-sm-2 control-label">Time arrived to client</label>
                <div class="col-sm-6 input-group bootstrap-timepicker timepicker">
                    <input id="timepicker2" type="text" name="time_arrived_to_client"
                           value="{{ form.time_arrived_to_client.value }}"
                           class="form-control input-small">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                </div>
            </div>
            <div class="form-group">
                <label for="time_left_client" class="col-sm-2 control-label">Time left client</label>
                <div class="col-sm-6 input-group bootstrap-timepicker timepicker">
                    <input id="timepicker3" type="text" name="time_left_client"
                           value="{{ form.time_left_client.value }}"
                           class="form-control input-small">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                </div>
            </div>
            <div class="form-group">
                <label for="time_back_to_terminal" class="col-sm-2 control-label">Time back to terminal</label>
                <div class="col-sm-6 input-group bootstrap-timepicker timepicker">
                    <input id="timepicker4" type="text" name="time_back_to_terminal" value="{{ form.timepicker.value }}"
                           class="form-control input-small">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                </div>
            </div>

            <div class="form-group">
                <label for="time_unloading" class="col-sm-2 control-label">Unloading time</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" name="time_unloading"
                           value="{{ form.time_unloading.value }}" placeholder="Unloading time">
                </div>
            </div>

            <div class="form-group">
                <label for="speedometer_at_leaving" class="col-sm-2 control-label">Speedometer at leaving</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" name="speedometer_at_leaving"
                           value="{{ form.speedometer_at_leaving.value }}"
                           placeholder="Speedometer at leaving">
                </div>
            </div>
            <div class="form-group">
                <label for="speedometer_at_arrival" class="col-sm-2 control-label">Speedometer at arrival</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" name="speedometer_at_arrival"
                           value="{{ form.speedometer_at_arrival.value }}"
                           placeholder="Speedometer at arrival">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-6">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

templates/transportation_management/index.html
{% extends 'base.html' %}

{% block content %}
INDEX
{% endblock content %}

templates/transportation_management/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/data_common.css' %}"/>
{% endblock extra_css %}

{% block content %}
    <h1>Travel Records</h1>
    <div class="travel-records-list">

        <table class="table table-hover">
            <thead>
            <tr>
                <th>No.</th>
                <th>Date</th>
                <th>Route</th>
                <th>Left Terminal</th>
                <th>Speedometer</th>
                <th>Arrived to Client</th>
                <th>Unloading Time</th>
                <th>Left Client</th>
                <th>Back to Terminal</th>
                <th>Speedometer</th>
                <th>Distance</th>
                <th>Fuel</th>
            </tr>
            </thead>
            <tbody>
            {% for report in travel_reports %}
                <tr>
                    <td>{{ report.id }}</td>
                    <td>{{ report.date }}</td>
                    <td>{{ report.route }}</td>
                    <td>{{ report.time_left_terminal }}</td>
                    <td>{{ report.speedometer_at_leaving }}</td>
                    <td>{{ report.time_arrived_to_client }}</td>
                    <td>{{ report.time_unloading }}</td>
                    <td>{{ report.time_left_client }}</td>
                    <td>{{ report.time_back_to_terminal }}</td>
                    <td>{{ report.speedometer_at_arrival }}</td>
                    <td>{{ report.distance }}</td>
                    <td>{{ report.fuel_consumed }}</td>
                </tr>
            {% endfor %}

            </tbody>

        </table>

    </div>
{% endblock content %}

templates/transportation_management/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
{% endblock extra_css %}

{% block content %}
<div class="login">
    <h1>Login</h1>
    <form action="{% url 'transportation-management:authenticate' %}" method="post">
        {% csrf_token %}
    	<input type="text" name="username" placeholder="Username" required="required" />
        <input type="password" name="password" placeholder="Password" required="required" />
        <button type="submit" class="btn btn-primary btn-block btn-large">Login</button>
    </form>
    <input type="hidden" name="next" value="{{ next }}" />
</div>
{% endblock content %}

templates/transportation_management/read.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/data_common.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/read.css' %}"/>
{% endblock extra_css %}

{% block content %}
    <h1>Travel Record to {{ travel_report.route }} on {{ travel_report.date }}</h1>
    <div class="travel-record-details">
        <dl class="dl-horizontal">
            <dt>Vehicle:</dt>
            <dd>{{ travel_report.vehicle.vehicle_name }}</dd>
            <dt>Route:</dt>
            <dd>{{ travel_report.route }}</dd>
            <dt>Date:</dt>
            <dd>{{ travel_report.date }}</dd>
            <dt>Left Terminal:</dt>
            <dd>{{ travel_report.time_left_terminal }}</dd>
            <dt>Arrived to Client:</dt>
            <dd>{{ travel_report.time_arrived_to_client }}</dd>
            <dt>Left Client:</dt>
            <dd>{{ travel_report.time_left_client }}</dd>
            <dt>Arrived back to terminal:</dt>
            <dd>{{ travel_report.time_back_to_terminal }}</dd>

            <dt>Took time unloading:</dt>
            <dd>{{ travel_report.time_unloading }}</dd>
            <dt>Start Speedomented</dt>
            <dd>{{ travel_report.speedometer_at_leaving }}</dd>
            <dt>End Speedomented</dt>
            <dd>{{ travel_report.speedometer_at_arrival }}</dd>
            <dt>Distance Traveled:</dt>
            <dd>{{ travel_report.distance }}</dd>
            <dt>Fuel Consumed:</dt>
            <dd>{{ travel_report.fuel_consumed }}</dd>
        </dl>
    </div>
{% endblock content %}